# Generated by Django 2.2.5 on 2025-08-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': '人物信息'},
        ),
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='描述信息'),
        ),
        migrations.AddField(
            model_name='people',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='people',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterModelTable(
            name='people',
            table='peopleinfo',
        ),
    ]
